//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceStringCounter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceStringCounter.IStringCounter")]
    public interface IStringCounter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCounter/CountStringAppearances", ReplyAction="http://tempuri.org/IStringCounter/CountStringAppearancesResponse")]
        int CountStringAppearances(string textPart, string fullText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCounter/CountStringAppearances", ReplyAction="http://tempuri.org/IStringCounter/CountStringAppearancesResponse")]
        System.Threading.Tasks.Task<int> CountStringAppearancesAsync(string textPart, string fullText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringCounterChannel : WcfClient.ServiceStringCounter.IStringCounter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringCounterClient : System.ServiceModel.ClientBase<WcfClient.ServiceStringCounter.IStringCounter>, WcfClient.ServiceStringCounter.IStringCounter {
        
        public StringCounterClient() {
        }
        
        public StringCounterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringCounterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringCounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountStringAppearances(string textPart, string fullText) {
            return base.Channel.CountStringAppearances(textPart, fullText);
        }
        
        public System.Threading.Tasks.Task<int> CountStringAppearancesAsync(string textPart, string fullText) {
            return base.Channel.CountStringAppearancesAsync(textPart, fullText);
        }
    }
}
