//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceDayOfWeek {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDayOfWeek.IDayOfWeekService")]
    public interface IDayOfWeekService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekService/ReturnDayOfWeekOnBulgarian", ReplyAction="http://tempuri.org/IDayOfWeekService/ReturnDayOfWeekOnBulgarianResponse")]
        string ReturnDayOfWeekOnBulgarian(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfWeekService/ReturnDayOfWeekOnBulgarian", ReplyAction="http://tempuri.org/IDayOfWeekService/ReturnDayOfWeekOnBulgarianResponse")]
        System.Threading.Tasks.Task<string> ReturnDayOfWeekOnBulgarianAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayOfWeekServiceChannel : WcfClient.ServiceDayOfWeek.IDayOfWeekService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayOfWeekServiceClient : System.ServiceModel.ClientBase<WcfClient.ServiceDayOfWeek.IDayOfWeekService>, WcfClient.ServiceDayOfWeek.IDayOfWeekService {
        
        public DayOfWeekServiceClient() {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfWeekServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReturnDayOfWeekOnBulgarian(System.DateTime date) {
            return base.Channel.ReturnDayOfWeekOnBulgarian(date);
        }
        
        public System.Threading.Tasks.Task<string> ReturnDayOfWeekOnBulgarianAsync(System.DateTime date) {
            return base.Channel.ReturnDayOfWeekOnBulgarianAsync(date);
        }
    }
}
